### ISSUE TITLE
Upgrade to Spring Security 5.5

### ISSUE THREAD

**Issue by robbydf** [spring-projects-experimental/spring-authorization-server#305]
**Expected Behavior**
Using Spring Security 5.5, the Spring Boot app containg Spring Security 5.5 and Spring Authorization 0.1.1 should start normally

**Current Behavior**
Spring Authorization Server produces a NullPointerException with Spring Security 5.5 (Which Spring Boot 2.5.0 uses) which prevents startup

**Context**
For context, I am developing a Spring Boot app containing both the authorization server and resource server. My workaround is to just use Spring Boot 2.5.0-RC1 which still uses Spring Security 5.5.0-RC1. I haven't yet tried anything else. 

Below is the stacktrace and logs. Hopefully the project will upgrade to Spring Security 5.5 in the next release.

```
:: Spring Boot ::                (v2.5.0)

2021-05-25 10:30:50.691+0800  INFO 2176 --- [kground-preinit] o.h.v.i.u.Version                        : {} HV000001: Hibernate Validator 6.2.0.Final
2021-05-25 10:30:50.854+0800  INFO 2176 --- [  restartedMain] c.p.b.BackendApplication		           : {} Starting BackendApplication using Java 16 on username-backend-laptop with PID 2176 (C:\Users\username\git\backend\app\out\production\classes started by username in C:\Users\username\git\backend)
2021-05-25 10:30:50.965+0800 DEBUG 2176 --- [  restartedMain] c.p.b.BackendApplication	  	           : {} Running with Spring Boot v2.5.0, Spring v5.3.7
2021-05-25 10:30:50.968+0800  INFO 2176 --- [  restartedMain] c.p.b.BackendApplication		           : {} The following profiles are active: dev,localhost
2021-05-25 10:30:51.113+0800  INFO 2176 --- [  restartedMain] o.s.b.d.r.ChangeableUrls                 : {} The Class-Path manifest attribute in C:\Users\username\.gradle\caches\modules-2\files-2.1\org.glassfish.ha\ha-api\3.1.12\59fbeca6cc196da8159e4957eabe49f23d1e691a\ha-api-3.1.12.jar referenced one or more files that do not exist: file:/C:/Users/username/.gradle/caches/modules-2/files-2.1/org.glassfish.ha/ha-api/3.1.12/59fbeca6cc196da8159e4957eabe49f23d1e691a/hk2.jar,file:/C:/Users/username/.gradle/caches/modules-2/files-2.1/org.glassfish.ha/ha-api/3.1.12/59fbeca6cc196da8159e4957eabe49f23d1e691a/hk2-core.jar,file:/C:/Users/username/.gradle/caches/modules-2/files-2.1/org.glassfish.ha/ha-api/3.1.12/59fbeca6cc196da8159e4957eabe49f23d1e691a/class-model.jar,file:/C:/Users/username/.gradle/caches/modules-2/files-2.1/org.glassfish.ha/ha-api/3.1.12/59fbeca6cc196da8159e4957eabe49f23d1e691a/config.jar,file:/C:/Users/username/.gradle/caches/modules-2/files-2.1/org.glassfish.ha/ha-api/3.1.12/59fbeca6cc196da8159e4957eabe49f23d1e691a/tiger-types.jar,file:/C:/Users/username/.gradle/caches/modules-2/files-2.1/org.glassfish.ha/ha-api/3.1.12/59fbeca6cc196da8159e4957eabe49f23d1e691a/bean-validator.jar,file:/C:/Users/username/.gradle/caches/modules-2/files-2.1/org.glassfish.ha/ha-api/3.1.12/59fbeca6cc196da8159e4957eabe49f23d1e691a/jtype.jar,file:/C:/Users/username/.gradle/caches/modules-2/files-2.1/org.glassfish.ha/ha-api/3.1.12/59fbeca6cc196da8159e4957eabe49f23d1e691a/auto-depends.jar,file:/C:/Users/username/.gradle/caches/modules-2/files-2.1/org.glassfish.ha/ha-api/3.1.12/59fbeca6cc196da8159e4957eabe49f23d1e691a/javax.inject.jar,file:/C:/Users/username/.gradle/caches/modules-2/files-2.1/org.glassfish.ha/ha-api/3.1.12/59fbeca6cc196da8159e4957eabe49f23d1e691a/asm-all-repackaged.jar,file:/C:/Users/username/.gradle/caches/modules-2/files-2.1/org.glassfish.ha/ha-api/3.1.12/59fbeca6cc196da8159e4957eabe49f23d1e691a/hk2-api.jar,file:/C:/Users/username/.gradle/caches/modules-2/files-2.1/org.glassfish.ha/ha-api/3.1.12/59fbeca6cc196da8159e4957eabe49f23d1e691a/osgi-resource-locator.jar,file:/C:/Users/username/.gradle/caches/modules-2/files-2.1/org.glassfish.ha/ha-api/3.1.12/59fbeca6cc196da8159e4957eabe49f23d1e691a/javax.inject.jar
2021-05-25 10:30:51.116+0800  INFO 2176 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : {} Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2021-05-25 10:30:52.068+0800  WARN 2176 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : {} For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2021-05-25 10:30:57.537+0800  INFO 2176 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : {} Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@58540e36' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-05-25 10:30:57.640+0800  INFO 2176 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : {} Bean 'principalRecordServiceImpl' of type [com.backend.security.PrincipalRecordServiceImpl] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-05-25 10:30:58.185+0800  INFO 2176 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : {} Bean 'userRepositoryImpl' of type [com.backend.db.jooq.repo.iam.UserRepositoryImpl] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-05-25 10:30:58.259+0800  INFO 2176 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : {} Bean 'backendSupportRepositoryImpl' of type [com.backend.db.jooq.repo.core.backendSupportRepositoryImpl] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-05-25 10:30:58.278+0800  INFO 2176 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : {} Bean 'permissionRepositoryImpl' of type [com.backend.db.jooq.repo.iam.PermissionRepositoryImpl] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-05-25 10:30:58.301+0800  INFO 2176 --- [  restartedMain] c.p.b.s.t.TimeServiceImpl                : {} Initialized normally
2021-05-25 10:30:58.302+0800  INFO 2176 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : {} Bean 'timeServiceImpl' of type [com.backend.service.time.TimeServiceImpl] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-05-25 10:30:58.304+0800  INFO 2176 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : {} Bean 'databasePermissionEvaluatorImpl' of type [com.backend.security.permission.DatabasePermissionEvaluatorImpl] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-05-25 10:30:58.306+0800  INFO 2176 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : {} Bean 'backend-permission-evaluator' of type [com.backend.security.permission.MainPermissionEvaluator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-05-25 10:30:58.308+0800  INFO 2176 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : {} Bean 'methodSecurityConfig' of type [com.backend.config.MethodSecurityConfig] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-05-25 10:30:58.314+0800  INFO 2176 --- [  restartedMain] c.p.b.c.MethodSecurityConfig             : {} MethodSecurityExpressionHandler initialized
2021-05-25 10:30:58.315+0800  INFO 2176 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : {} Bean 'createExpressionHandler' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-05-25 10:30:58.324+0800  INFO 2176 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : {} Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-05-25 10:30:59.279+0800  INFO 2176 --- [  restartedMain] o.s.b.w.e.t.TomcatWebServer              : {} Tomcat initialized with port(s): 8080 (http)
2021-05-25 10:30:59.305+0800  INFO 2176 --- [  restartedMain] o.a.c.h.Http11NioProtocol                : {} The ["http-nio-8080"] connector has been configured to support HTTP upgrade to [h2c]
2021-05-25 10:30:59.306+0800  INFO 2176 --- [  restartedMain] o.a.c.h.Http11NioProtocol                : {} Initializing ProtocolHandler ["http-nio-8080"]
2021-05-25 10:30:59.308+0800  INFO 2176 --- [  restartedMain] o.a.c.c.StandardService                  : {} Starting service [Tomcat]
2021-05-25 10:30:59.308+0800  INFO 2176 --- [  restartedMain] o.a.c.c.StandardEngine                   : {} Starting Servlet engine: [Apache Tomcat/9.0.46]
2021-05-25 10:30:59.609+0800  INFO 2176 --- [  restartedMain] o.a.c.c.C.[.[.[/]                        : {} Initializing Spring embedded WebApplicationContext
2021-05-25 10:30:59.609+0800  INFO 2176 --- [  restartedMain] w.s.c.ServletWebServerApplicationContext : {} Root WebApplicationContext: initialization completed in 8490 ms
2021-05-25 10:30:59.939+0800  INFO 2176 --- [  restartedMain] c.p.b.c.AuthorizationServerConfig        : {} InMemoryOAuth2AuthorizationService initialized
2021-05-25 10:31:00.180+0800  INFO 2176 --- [  restartedMain] o.s.a.f.CglibAopProxy                    : {} Unable to proxy interface-implementing method [public final void org.springframework.web.filter.GenericFilterBean.init(javax.servlet.FilterConfig) throws javax.servlet.ServletException] because it is marked as final: Consider using interface-based JDK proxies instead!
2021-05-25 10:31:00.197+0800  INFO 2176 --- [  restartedMain] c.p.b.c.W.SecureWebSecurityConfig        : {} Security initialized
2021-05-25 10:31:00.619+0800  INFO 2176 --- [  restartedMain] c.p.b.s.u.UuidServiceImpl                : {} Initialized normally
2021-05-25 10:31:00.747+0800 DEBUG 2176 --- [  restartedMain] c.p.b.s.LoginPageFilter                  : {} Filter 'loginPageFilter' configured for use
2021-05-25 10:31:00.748+0800 DEBUG 2176 --- [  restartedMain] f.ExpiredBearerTokenAuthenticationFilter : {} Filter 'expiredBearerTokenAuthenticationFilter' configured for use
2021-05-25 10:31:00.754+0800 DEBUG 2176 --- [  restartedMain] .UsernamePasswordOtpAuthenticationFilter : {} Filter 'usernamePasswordOtpAuthenticationFilter' configured for use
2021-05-25 10:31:00.891+0800  WARN 2176 --- [  restartedMain] o.s.b.c.c.a.DefaultBatchConfigurer       : {} No transaction manager was provided, using a DataSourceTransactionManager
2021-05-25 10:31:00.976+0800  INFO 2176 --- [  restartedMain] c.z.h.HikariDataSource                   : {} HikariPool-1 - Starting...
2021-05-25 10:31:01.372+0800  INFO 2176 --- [  restartedMain] c.z.h.HikariDataSource                   : {} HikariPool-1 - Start completed.
2021-05-25 10:31:01.399+0800  INFO 2176 --- [  restartedMain] o.s.b.c.r.s.JobRepositoryFactoryBean     : {} No database type set, using meta data indicating: POSTGRES
2021-05-25 10:31:01.459+0800  INFO 2176 --- [  restartedMain] o.s.b.c.l.s.SimpleJobLauncher            : {} No TaskExecutor has been set, defaulting to synchronous executor.
2021-05-25 10:31:01.466+0800  INFO 2176 --- [  restartedMain] p.b.c.C.NonProdLocalhostCustomProperties : {} Initialized
2021-05-25 10:31:01.471+0800  INFO 2176 --- [  restartedMain] c.p.b.c.JacksonConfig                    : {} Initialized
2021-05-25 10:31:01.510+0800  INFO 2176 --- [  restartedMain] c.p.b.c.ValidationConfig                 : {} Initialized
2021-05-25 10:31:02.782+0800  INFO 2176 --- [  restartedMain] c.p.b.c.JmsConfig                        : {} JMS prefetch policy set
2021-05-25 10:31:02.793+0800  INFO 2176 --- [  restartedMain] c.p.b.c.JmsConfig                        : {} JMS configured
2021-05-25 10:31:03.049+0800  INFO 2176 --- [  restartedMain] c.p.b.c.AuthorizationServerConfig        : {} InMemoryRegisteredClientRepository configured
2021-05-25 10:31:03.068+0800 DEBUG 2176 --- [  restartedMain] c.p.b.s.a.JwksGeneratorUtil              : {} Generating RSA key pair
2021-05-25 10:31:03.556+0800  INFO 2176 --- [  restartedMain] c.p.b.c.CacheConfig                      : {} Initialized CacheManager for databases
2021-05-25 10:31:03.561+0800  INFO 2176 --- [  restartedMain] c.p.b.c.CacheConfig                      : {} Initialized CacheManager for half day caches
2021-05-25 10:31:03.764+0800  INFO 2176 --- [  restartedMain] c.p.b.c.AuthorizationServerConfig        : {} OAuth2AuthorizationServer security configured
2021-05-25 10:31:03.797+0800  INFO 2176 --- [  restartedMain] o.s.s.w.DefaultSecurityFilterChain       : {} Will secure Ant [pattern='/test/**'] with []
2021-05-25 10:31:04.054+0800  INFO 2176 --- [  restartedMain] c.p.b.c.WebConfig                        : {} Configuring CORS settings
2021-05-25 10:31:04.058+0800  INFO 2176 --- [  restartedMain] c.p.b.c.WebConfig                        : {} Configured CORS settings
2021-05-25 10:31:04.294+0800  INFO 2176 --- [  restartedMain] o.s.b.a.w.s.WelcomePageHandlerMapping    : {} Adding welcome page template: index
2021-05-25 10:31:06.015+0800  INFO 2176 --- [  restartedMain] o.s.b.a.e.w.EndpointLinksResolver        : {} Exposing 14 endpoint(s) beneath base path '/actuator'
2021-05-25 10:31:06.154+0800  WARN 2176 --- [  restartedMain] ConfigServletWebServerApplicationContext : {} Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.springframework.security.config.annotation.web.builders.FilterOrderRegistration.getOrder(java.lang.Class)" is null
2021-05-25 10:31:06.157+0800  INFO 2176 --- [  restartedMain] c.z.h.HikariDataSource                   : {} HikariPool-1 - Shutdown initiated...
2021-05-25 10:31:06.161+0800  INFO 2176 --- [  restartedMain] c.z.h.HikariDataSource                   : {} HikariPool-1 - Shutdown completed.
2021-05-25 10:31:06.178+0800  INFO 2176 --- [  restartedMain] o.a.c.c.StandardService                  : {} Stopping service [Tomcat]
2021-05-25 10:31:06.230+0800  INFO 2176 --- [  restartedMain] ConditionEvaluationReportLoggingListener : {} 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-05-25 10:31:06.301+0800 ERROR 2176 --- [  restartedMain] o.s.b.SpringApplication                  : {} Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.springframework.security.config.annotation.web.builders.FilterOrderRegistration.getOrder(java.lang.Class)" is null
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:337) [spring-boot-2.5.0.jar:2.5.0]
	at com.backend.backendBackendApplication.main(backendBackendApplication.java:20) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.5.0.jar:2.5.0]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.springframework.security.config.annotation.web.builders.FilterOrderRegistration.getOrder(java.lang.Class)" is null
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.7.jar:5.3.7]
	... 24 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.springframework.security.config.annotation.web.builders.FilterOrderRegistration.getOrder(java.lang.Class)" is null
	at org.springframework.security.config.annotation.web.builders.HttpSecurity.addFilterAtOffsetOf(HttpSecurity.java:2654) ~[spring-security-config-5.5.0.jar:5.5.0]
	at org.springframework.security.config.annotation.web.builders.HttpSecurity.addFilterAfter(HttpSecurity.java:2645) ~[spring-security-config-5.5.0.jar:5.5.0]
	at org.springframework.security.config.annotation.web.builders.HttpSecurity.addFilterAfter(HttpSecurity.java:134) ~[spring-security-config-5.5.0.jar:5.5.0]
	at org.springframework.security.config.annotation.web.configurers.oauth2.server.authorization.OAuth2AuthorizationServerConfigurer.configure(OAuth2AuthorizationServerConfigurer.java:279) ~[spring-security-oauth2-authorization-server-0.1.1.jar:0.1.1]
	at org.springframework.security.config.annotation.web.configurers.oauth2.server.authorization.OAuth2AuthorizationServerConfigurer.configure(OAuth2AuthorizationServerConfigurer.java:90) ~[spring-security-oauth2-authorization-server-0.1.1.jar:0.1.1]
	at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.configure(AbstractConfiguredSecurityBuilder.java:349) ~[spring-security-config-5.5.0.jar:5.5.0]
	at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.doBuild(AbstractConfiguredSecurityBuilder.java:303) ~[spring-security-config-5.5.0.jar:5.5.0]
	at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:38) ~[spring-security-config-5.5.0.jar:5.5.0]
	at org.springframework.security.config.annotation.web.builders.WebSecurity.performBuild(WebSecurity.java:285) ~[spring-security-config-5.5.0.jar:5.5.0]
	at org.springframework.security.config.annotation.web.builders.WebSecurity.performBuild(WebSecurity.java:83) ~[spring-security-config-5.5.0.jar:5.5.0]
	at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.doBuild(AbstractConfiguredSecurityBuilder.java:305) ~[spring-security-config-5.5.0.jar:5.5.0]
	at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:38) ~[spring-security-config-5.5.0.jar:5.5.0]
	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.springSecurityFilterChain(WebSecurityConfiguration.java:127) ~[spring-security-config-5.5.0.jar:5.5.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.7.jar:5.3.7]
	... 24 more


Process finished with exit code 0
```

**Comment by anoopgarlapati** [comment]
https://github.com/spring-projects-experimental/spring-authorization-server/blob/5e0fe9c8622b6f31de86e981cb10f0e425c425a3/oauth2-authorization-server/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/authorization/OAuth2AuthorizationServerConfigurer.java#L279 
Looks like its due to this broken behavior reported in https://github.com/spring-projects/spring-security/issues/9787

**Comment by robbydf** [comment]
got it. will close this then
